export type character = {
    name: string,
    japanese?: string,
    alter?: string,
    alterJapanese?: string,
    alias? : string,
    alterAlias?: string,
    series: number,
    ace: string,
    id: number,
    role: string,
    kuri?: string,
    avatar?: string,
    color?: string,
}