import type { character } from "../../types/character"

const CHARACTERS: character[] = [
    {   name: 'Yugi Muto',
        japanese: 'Yugi Mutou',
        alter: 'Yami Yugi',
        alterJapanese: 'Dark Yugi',
        series: 1,
        ace: 'Dark Magician',
        id: 46986414,
        role: 'main protagonist',
        kuri: 'Kuriboh',
        avatar: 'https://ms.yugipedia.com//thumb/2/2d/YugiMuto-DSOD-DULI-CutIn.png/120px-YugiMuto-DSOD-DULI-CutIn.png',
        color: 'ring-ygonormal bg-gradient-to-br from-ygonormal to-zinc-500'
    },
    {   name: 'Seto Kaiba',
        series: 1,
        ace: 'Blue-Eyes White Dragon',
        id: 89631139,
        role: 'main rival',
    },
    {   name: 'Joey Wheeler',
        japanese: 'Katsuya Jonouchi',
        series: 1,
        ace: 'Red-Eyes Black Dragon',
        id: 74677422,
        role: 'main friend',
    },
    {   name: 'Yami Marik',
        alter: 'Yami Marik',
        alterJapanese: 'Dark Marik',
        series: 1,
        ace: 'The Winged Dragon of Ra',
        id: 10000010,
        role: 'main antihero',
        avatar: 'https://ms.yugipedia.com//thumb/1/13/YamiMarik-DULI-CutIn.png/120px-YamiMarik-DULI-CutIn.png',
        color: 'ring-ygoritual bg-gradient-to-br from-ygoritual to-zinc-500'
    },
    {   name: 'The Supreme King',
        alias: 'Haou',
        series: 2,
        ace: 'Evil HERO Malicious Fiend',
        id: 46986414,
        role: 'main friend',
        avatar: 'https://ms.yugipedia.com//thumb/e/e9/SupremeKingJaden-DULI-CutIn.png/120px-SupremeKingJaden-DULI-CutIn.png',
        color: 'ring-ygofusion bg-gradient-to-br from-ygofusion to-zinc-500'
    },
    {   name: 'Yusei Fudo',
        japanese: 'Yusei Fudou',
        series: 3,
        ace: 'Stardust Dragon',
        id: 46986414,
        role: 'main protagonist',
        kuri: 'Junkuriboh',
        avatar: 'https://static.wikia.nocookie.net/yugioh/images/7/7e/Summoning-DULI-YuseiFudo.png',
        color: 'ring-ygosynchro bg-gradient-to-br from-ygosynchro to-zinc-500'
    },
    {   name: 'Reginald Kastle',
        alias: 'Shark',
        series: 4,
        ace: 'Number 101: Silent Honor ARK',
        id: 46986414,
        role: 'main friend',
        avatar: 'https://static.wikia.nocookie.net/yugioh/images/c/c9/Summoning-DULI-ReginaldSharkKastle.png',
        color: 'ring-ygoxyz bg-gradient-to-br from-ygoxyz to-zinc-500'
    },
    {   name: 'Declan Akaba',
        japanese: 'Reiji Akaba',
        series: 5,
        ace: 'D/D/D Doom King Armaggeddon',
        id: 46986414,
        role: 'main rival',
        avatar: 'https://ms.yugipedia.com//thumb/f/f5/DeclanAkaba-DULI-CutIn.png/120px-DeclanAkaba-DULI-CutIn.png',
        color: 'ring-ygospell bg-gradient-to-br from-ygospell to-zinc-500'
    },
    {   name: 'Skye Zaizen',
        alias: 'Blue Maiden',
        series: 6,
        ace: 'Marincess',
        id: 46986414,
        role: 'main rival',
        avatar: 'https://ms.yugipedia.com//thumb/8/87/BlueAngel-DULI-CutIn.png/120px-BlueAngel-DULI-CutIn.png',
        color: 'ring-ygolink bg-gradient-to-br from-ygolink to-zinc-500'
    },
    {   name: 'Yuga Ohda',
        alias: 'Blue Maiden',
        series: 7,
        ace: 'Marincess',
        id: 46986414,
        role: 'main rival',
        avatar: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/43b29b69-3bd3-42fe-9c9b-27b69b86fcb0/ddqe0t2-9ec82ac7-2b5d-486c-bc84-25547d13b0c9.png/v1/fill/w_800,h_800/yuga_odo__full_render____yu_gi_oh__sevens_by_kogadiamond1080_ddqe0t2-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODAwIiwicGF0aCI6IlwvZlwvNDNiMjliNjktM2JkMy00MmZlLTljOWItMjdiNjliODZmY2IwXC9kZHFlMHQyLTllYzgyYWM3LTJiNWQtNDg2Yy1iYzg0LTI1NTQ3ZDEzYjBjOS5wbmciLCJ3aWR0aCI6Ijw9ODAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.pC_7obdbYUQhJFDDBZ2707l4_EB6ykk8xnH5jwCXyTQ',
        color: 'ring-ygoeffect bg-gradient-to-br from-ygoeffect to-zinc-500'
    },
    {   name: 'Yudias Velgear',
        alias: 'Blue Maiden',
        series: 8,
        ace: 'Marincess',
        id: 46986414,
        role: 'main rival',
        avatar: 'https://ms.yugipedia.com//thumb/9/94/YudiasVelgear-Full.png/175px-YudiasVelgear-Full.png',
        color: 'ring-ygotrap bg-gradient-to-br from-ygotrap to-zinc-500'
    },
    {
        name: 'Unknown Duelist',
        series: 9,
        ace: 'Sapeee',
        id: 69,
        role: 'chupa vergas',
        avatar: 'https://ms.yugipedia.com//thumb/3/31/UnknownDuelist-DULI.png/257px-UnknownDuelist-DULI.png',
        color: 'ring-ygotoken bg-gradient-to-br from-ygotoken to-zinc-500'
    },
    {
        name: 'Yuya Sakaki',
        series: 9,
        ace: 'Sapeee',
        id: 69,
        role: 'chupa vergas',
        avatar: 'https://ms.yugipedia.com//thumb/3/31/UnknownDuelist-DULI.png/257px-UnknownDuelist-DULI.png',
        color: 'ring-ygotoken bg-gradient-to-br from-ygotoken to-zinc-500'
    }
]

export default CHARACTERS