const yugiTypes = {
    aqua: 'GiGooeyDaemon',
    beast: 'GiBeastEye',
    beastWarrior: 'GiWerewolf',
    celestialWarrior: 'GiElfHelmet',
    charisma: 'GiClown',
    continuousSpell: 'GiInfinity',
    continuousTrap: 'GiOverInfinity',
    creatorGod: 'GiAngelWings',
    counter: 'GiArrowDunk',
    cyberse: 'GiCyberEye',
    cyborg: 'GiCyborgFace',
    dinosaur: 'GiDinosaurRex',
    divineBeast: 'GiHorus',
    dragon: 'GiSpikedDragonHead',
    equip: 'GiBattleGear',
    fairy: 'GiAngelOutfit',
    field: 'GiCompass',
    fiend: 'GiDaemonSkull',
    fish: 'GiSharkJaws',
    galaxy: 'GiGalaxy',
    highDragon: 'GiDoubleDragon',
    human: 'GiEgyptianWalk',
    illusion: 'GiEyeOfHorus',
    insect: 'GiSpiderAlt',
    machine: 'GiRobotGolem',
    magicalKnight: 'GiOverlordHelm',
    normalSpell: 'GiSpellBook',
    normalTrap: 'GiWolfTrap',
    omegaPsychic: 'GiAndroidMask',
    plant: 'GiVenusFlytrap',
    psychic: 'GiPsychicWaves',
    pyro: 'GiPyromaniac',
    quickPlay: 'GiLightningTrio',
    reptile: 'GiSandSnake',
    ritual: 'GiFireShrine',
    rock: 'GiRockGolem',
    seaSerpent: 'GiSeaCreature',
    spellcaster: 'FaHatWizard',
    thunder: 'GiThunderSkull',
    warrior: 'GiSpartanHelmet',
    wingedBeast: 'GiEagleEmblem',
    wyrm: 'GiDrakkarDragon',
    zombie: 'GiRaiseZombie',
}

const yugiAttributes = {
    DARK: 'GiEvilMoon',
    DIVINE: 'GiAnkh',
    EARTH: 'GiStonePile',
    FIRE: 'GiSmallFire',
    LAUGH: 'GiDiamondsSmile',
    LIGHT: 'GiEnlightenment',
    SPELL: 'GiMagicPortal',
    TRAP: 'GiTrapMask',
    WATER: 'GiWaterSplash',
    WIND: 'GiWhirlwind',
}